# Generated by Django 3.1.3 on 2020-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cooperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperation',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
