# Generated by Django 3.1.3 on 2020-11-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='adress',
            new_name='address',
        ),
    ]
