# Generated by Django 3.1.3 on 2020-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201120_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='name',
            field=models.CharField(default='testproject', max_length=255),
            preserve_default=False,
        ),
    ]
