# Generated by Django 3.1.3 on 2020-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201118_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperatorprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
