# Generated by Django 3.1.3 on 2020-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cooperation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperation',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
