# Generated by Django 3.1.3 on 2020-11-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cooperation_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperation',
            old_name='org_worker',
            new_name='org_staff',
        ),
    ]
