# Generated by Django 3.1.3 on 2020-11-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('cooperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cooperatorprofile')),
            ],
        ),
    ]
