# Generated by Django 3.1.3 on 2020-11-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201126_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='user',
        ),
    ]
